### ISSUE TITLE
Offline state is not rehydrating

### ISSUE THREAD

**Issue by dabit1** [redux-offline/redux-offline#59]
When actions are queued, after restart the app the state.offline.outbox is empty.

**Comment by jevakallio** [comment]
Which version are you using?

**Comment by jevakallio** [comment]
Can you also show how you are configuring the offline store / enhancer?

**Comment by dabit1** [comment]
Hi @jevakallio !

I'm using the last version (1.1.0). My configuration is:

```
import thunkMiddleware from 'redux-thunk'
import { applyMiddleware } from 'redux'
import rootReducer from './reducers'
import { createOfflineStore } from 'redux-offline'
import defaultConfig from 'redux-offline/lib/defaults'
import RestApi from 'src/config/restapi'

const createStore = persistCallback => createOfflineStore(
  rootReducer, 
  undefined,
  applyMiddleware(
    thunkMiddleware
  ),
  {
   ...defaultConfig,
   effect: (effect, action) => {
     return RestApi(effect.language, effect.tokenData)[effect.method](...effect.params)
   },
   rehydrate: true,
   persistCallback
  }
)

export default createStore
```

All what I'm doing is send an action with meta.offline with effect, commit and rollback attributes when the cellullar is with data status in "Unregistered (off)", then that action is queued but when I restart the app the state.offline.outbox is empty.

Thanks and great job!

David

**Comment by dabit1** [comment]
Another question is, when the requests are retried and my data status become to "Unregistered (off)", and after returns to "Home", Should not reset the decaying schedule to the beggining instead of continue from the last step where it was (for example, "After 1 minute")? I don't know if I'm explaining it well, sorry :P

**Comment by jevakallio** [comment]
Okay, everything in your configuration looks good. I'll try to reproduce this and see what's going on.

**Comment by dabit1** [comment]
I updated RN and every package to latest version and the problem persists, any news?

**Comment by DylanGriffith** [comment]
We're noticing the same issue. Will try to create a simple case to post but we seemed to be noticing that the requests that we're pending (ie. retrying) were lost after restarting the app on RN. Looking at the state seemed to be suggesting the `offline.outbox` was empty after a restart even though it had things before the restart.

Might be worth noting our config has `{...offlineConfig, persistOptions: {whitelist: ['offline']}`

**Comment by DylanGriffith** [comment]
I've created a minimal failing example using a simple web react app using `create-react-app` [here](https://github.com/DylanGriffith/test-redux-offline) . This is a web app (ie. not React Native) and it still has the same issue of the offline not being reloaded correctly from local storage.

Here are the steps to reproducing the issue:

Setup:
```
yarn
```

Run:
```
yarn start
```

Test redux-persist not reloading `offline.outbox`:

1. Load the app http://localhost:3000/
2. Click the button
3. Notice the outbox count goes up
4. Check the dev console notice the failed requests and retries being logged
5. Refresh the page
6. Notice the outbox count goes back to 0
7. Check the dev console notice there is no failed requests or retries being logged

Also if you want to see the configuration steps I did [this commit](https://github.com/DylanGriffith/test-redux-offline/commit/dbf6f5787e26968dce5bb35a46160d6512c28e23) describes just the redux/redux-offline setup.

**Comment by DylanGriffith** [comment]
Something that may help with fixing this is that I was able to make the rehydration start to work again by commenting out the following code in `src/updater.js`:

```
  if (action.type === PERSIST_REHYDRATE) {
    return { ...state, busy: false };
  }
```

Only problem is I'm not really sure what this is meant to do and why it would be having an effect on the outbox considering it only seems to update the `busy`.

**Comment by DylanGriffith** [comment]
I found the following in the `redux-persist` docs:

> While auto rehydration works out of the box, individual reducers can opt in to handling their own rehydration, allowing for more complex operations like data transforms and cache invalidation. Simply define a handler for the rehydrate action in your reducer, and if the state is mutated, auto rehydrate will skip that key.

So I think that tells me because `PERSIST_REHYDRATE` is being handled it is skipping  in autorehydrate. In order to make the rehydration behave correctly we probably need to do the rehydration in that reducer since autorehydrate will be skipped.

**Comment by DylanGriffith** [comment]
I'm thinking the following may work:
```
if (action.type === PERSIST_REHYDRATE) {
    return { ...action.payload.offline, busy: false };
}
```

**Comment by dabit1** [comment]
Hi @DylanGriffith, It seems that the problem is there. But I don't know why is setting busy to false when PERSIST_REHYDRATE is fired. @jevakallio What do you think?

**Comment by McPo** [comment]
@DylanGriffith Thanks for the investigatory work. Your suggestion seems to be the correct solution, would it be possible for you to get a PR created, so that @jevakallio can easily merge it. You can just use the built in github editor to change that single line.

This seems to be a significant issue and warrants a hotfix IMO.

**Comment by McPo** [comment]
Actually, there is one issue with @DylanGriffith, solution. It doesn't handle the case that there is nothing to hydrate `action.payload.offline === undefined`. Therefore it should be

```
if (action.type === PERSIST_REHYDRATE) {
    if (action.payload.offline) delete action.payload.offline.online;
    return { ...state, ...action.payload.offline, busy: false };
}
```

**Comment by botraunak** [comment]
@McPo I ran into the same issue, thanks for the wonderful solution, worked perfectly for me!

**Comment by tomsowerby** [comment]
I was seeing the same thing where the outbox was not repopulating, this solution helped with that.
However, I'm also seeing an issue on occasion where the outbox seems to be rehydrated after a refresh, but then doesn't appear to be retrying the outbox effects.

I've played with adding more to the PERSIST_REHYDRATE updater to "reset" a few more attributes, which seems to solve it, but I could do with some sense checking from others that know a bit more about it.

    return {
        ...state, 
        ...action.payload.offline, 
        busy: false, 
        lastTransaction: 0, 
        retryScheduled: false, 
        retryCount: 0, 
        retryToken: 0 
    }

Perhaps it could be included in the solution if others find it useful?

**Comment by connercms** [comment]
I am experiencing this issue on ^2.0.0. Was this fixed? My store init and config code looks like 
```
const store = createStore(
  reducers,
  undefined,
  compose(applyMiddleware(thunk, logger), offline(offlineConfig))
)

export default class Setup extends Component {
  constructor(props) {
    super(props)
    this.state = {
      rehydrated: false
    }
  }

  componentWillMount() {
    persistStore(store, { storage: AsyncStorage }, () => {
      this.setState({ rehydrated: true })
    })
  }

  render = () =>
    !this.state.rehydrated ? (
      <SplashScreen />
    ) : (
      <Provider store={store}>
        <MyApp />
      </Provider>
    )
}
```

However "offline" doesn't rehydrate properly when restarting app and I lose queued actions. Everything else appears to rehydrate fine.

Using redux-persist ^4.9.1, RN ^0.49.3, react-redux ^5.0.6

**Comment by ForumT** [comment]
Hi I installed the latest redux-offline version and the issue is still there. When I refresh the page my outbox empties and my data is lost. I used the McPo solution but with this the requests are sent from many open tabs of the application creating multiple records. Is there a solution for this :(

**Comment by wacii** [comment]
@ForumT The issue here has been addressed. If the actions are not rehydrating for you there is another problem. Which means I'll need to see some code to see what is happening.

Please open a new issue with code reproducing the bug.

As for the multiple open tabs each sending requests, I hadn't thought of that, but can see it being a problem. I would open a separate issue for that as well.

**Comment by mojodev** [comment]
this issue still exist in V2.4.0. any one got solution for this issue ?

in my case, state.offline.outbox has data once i kill the app(it works fine). but second time when i kill the app and started again state.offline.outbox is showing empty. any one have any solution for this issue ?
